---
id: scope
title: Scope
---

We have talked about how Effection operations allow you to bundle setup and
teardown as a unit so that automatic cleanup is _guaranteed_, but how are
they able to do this, and how can you implement your own operations which clean
up after themselves?

### Scope of a lifetime

Every operation in Effection runs in the context of an associated scope which
places a hard limit on how long it will live. For example, the script below uses
the [`spawn()`][spawn] operation to run an operation concurrently that counts to
ten, outputting one number every second. It then sleeps for five seconds before
returning;

```js
import { main, sleep, spawn } from "effection";

await main(function* () { // <- parent scope
  yield* spawn(function* () { // <- child scope
    for (let i = 1; i = 10; i++) {
      yield* sleep(1000);
      console.log(i);
    }
  });

  yield* sleep(5000);
});
```

It may suprise you to learn that this script will only output _five_
numbers, not ten. This is because the main operation completes after
just five seconds, and as a result its scope, and every scope it
contains, is halted. This in turn means that our counting operation is
shutdown and outputs nothing more.

>ðŸ’¡Key Concept: _no operation may outlive its scope_.

This simple rule is incredibly powerful! It means that you can create all kinds
of dynamic, concurrent processes, but the moment that they pass out of scope and
are no longer needed, they are immediately stopped. If we think about it, this
is very similar to the concept of lexical scope in JavaScript with which we're
already familiar.

```js
{
  let left = 1;
  let right = 2;
  console.log(`${left} + ${right} = ${left + right}`)
}

console.log(left) // <= ReferenceError left is not defined
```

In the snippet above, we allocate two number variables: `left` and `right`.
Inside the "curlys" we can read and write from them all we want, but once we
leave, JavaScript is going to deallocate them and the memory they hold
automatically for us and because of that, we aren't allowed to touch
them ever again. We describe this situation saying that the variables
have "passed out of scope" and so any resources they hold (in this case
computer memory) can be automatically reclaimed.

Effection applies this very same principle to entire operations, not just
variable references. Because of this, once the outcome of an operation becomes
known, or it is no longer needed, that operation and all of the operations it
contains can be safely shut down.

### The Three Outcomes

There are only three ways an operation may pass out of scope.

1. **return** the operation completes to produce a value.
2. **error** the operation fails and exits with an exception.
3. **halt** due to a return, error or a halt of a related operation, an
operation is halted.

No matter which one of these happens, We'll consider each of these .

```ts
import { sleep } from "effection";

function* slowly(value) {
  yield* sleep(1_000);
  return value;
}

let message = await run(function* add() {
  let left = yield* call(function*() {
    yield* sleep(1_000);
    return 1;
  });

  let right = yield* call(function*() {})
  return left + right;
});
```

### Suspend (it's not the end)

In order to understand the lifecycle of a Task, we must first understand the
concept of halting a Task.

In Effection, any task can be halted:

``` javascript
import { run } from 'effection';

let task = run(function*() {
  yield* suspend();
});

await task.halt();
```

Or:

``` javascript
await main(function*() {
  let task = yield spawn(suspend);
  yield* task.halt();
});
```

Halting a Task means that the task itself is cancelled, it also causes any Task
that has been spawned from the Task to be halted.

We have previously mentioned that when an error occurs in a Task, the task
becomes errored, and also causes its parent to become errored. However, if a
Task is halted, the parent task is unaffected.

### Return

If a Task is driving a generator, we call `return()` on the generator. This
behaves somewhat similarly to if you would replace the `yield` statement with a
`return` statement.

Let's look at an example where a task is suspended using `yield` with no
arguments and what happens when we call `halt` on it:

``` javascript
import { main } from 'effection';

let task = main(function*() {
  yield; // we will "return" from here
  console.log('we will never get here');
});

task.halt();
```

This would behave somewhat similarly to the following:

``` javascript
import { main } from 'effection';

main(function*() {
  return;
  console.log('we will never get here');
});
```

Crucially, when this happens, just like with a regular `return`, we can use `try/finally`:

``` javascript
import { main, sleep } from 'effection';

let task = main(function*() {
  try {
    yield // we will "return" from here
  } finally {
    console.log('yes, this will be printed!');
  }
});

task.halt();
```

### Cleaning up

We can use this mechanism to run code as a Task is shutting down, whether it
happens because the Task completes successfully, it becomes halted, or it is
rejected due to an error.

Imagine that we're doing something with an HTTP server, and we're using node's
`createServer` function. In order to properly clean up after ourselves, we
should call `close()` on the server when we're done.

Using Effection and `try/finally`, we could do something like this:

``` javascript
import { main } from 'effection';
import { createServer } from 'http';

let task = main(function*() {
  let server = createServer();
  try {
    // in real code we would do something more interesting here
    yield;
  } finally {
    server.close();
  }
});

task.halt();
```

### Asynchronous halt

You might be wondering what happens when we `yield` in a finally block. In
fact, Effection handles this case for you:

``` javascript
import { main, sleep } from 'effection';

let task = main(function*() {
  try {
    yield;
  } finally {
    console.log('this task is slow to halt');
    yield sleep(2000);
    console.log('now it has been halted');
  }
});

task.halt();
```

While performing asynchronous operations while halting is sometimes necessary,
it is good practice to keep halting speedy and simple. We recommend avoiding
expensive operations during halt where possible, and avoiding throwing any
errors during halting.

### Ensure

Sometimes you want to avoid the rightward drift of using lots of `try/finally` blocks.
The `ensure` operation that ships with Effection can help you clean up this type of code.

The following behaves identically to our `try/finally` implementation above:

``` javascript
import { main, ensure } from 'effection';
import { createServer } from 'http';

let task = main(function*() {
  let server = createServer();
  yield ensure(() => server.close());

  // in real code we would do something more interesting here
  yield;
});

task.halt();
```

### Abort Signal

While cancellation and teardown is handled automatically for us as long as we
are using Effection operations, what do we do when we want to integrate with a
3rd party API? One very common answer is to use the JavaScript standard
[`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)
which can broadcast an event whenever it is time for an operation to be
cancelled. Effection makes it easy to create abort signals, and pass them around
so that they can notify dependencies whenever an operation terminates.

To create an abort signal, we use the `createAbortSignal` that comes with
Effection.

`AbortSignal`s instantiated with the `createAbortSignal()` operation are
implicitly bound to the task in which they were created, and whenever that task
ceases running, they will emit an `abort` event.

``` javascript
import { main, sleep, createAbortSignal } from 'effection';

main(function*() {
  let signal = yield createAbortSignal();

  signal.addEventListener('abort', () => console.log('done!'));

  yield sleep(5000);
  // prints 'done!'
});
```

It is very common (though not universal) that APIs which perform
asynchronous operations will accept an `AbortSignal` in order to make
sure those operations go away if needed. For example, the standard
[`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch) function
accepts an abort signal to cancel itself when needed.

``` javascript
function* request(url) {
  let signal = yield createAbortSignal();
  let response = yield fetch('/some/url', { signal });
  if (response.ok) {
    return yield response.text();
  } else {
    throw new Error(`failed: ${ response.status }: ${response.statusText}`);
  }
}
```

Now, no matter what happens, when the `request` operation is completed (or
cancelled), the HTTP request is guaranteed to be shut down.

[spawn]: https://deno.land/x/effection/mod.ts?s=spawn
